### ISSUE TITLE
『找出Java最耗CPU或IO的线程』博文中，推荐自动化脚本 show-busy-java-threads

### ISSUE THREAD

**Issue by oldratlee** [emacsist/emacsist.github.io#2]
[找出Java最耗CPU或IO的线程](https://emacsist.github.io/2015/11/23/%E6%89%BE%E5%87%BAjava%E6%9C%80%E8%80%97cpu%E6%88%96io%E7%9A%84%E7%BA%BF%E7%A8%8B/)博文很不很！ 👍 
 
推荐自动化脚本 [show-busy-java-threads](https://github.com/oldratlee/useful-scripts/blob/master/docs/java.md#beer-show-busy-java-threads)，可以看看，作为工具附到文章中。

**Comment by emacsist** [comment]
亲测很好用.  我也更新了 blog 并引用了. 

免去了这么烦琐的命令执行和计算, 直接用这个自动化脚本效率更高, 灵活性也更好点. 

感谢
